import { defaultLandingData as serbianLandingData } from './landingContent.js'

const englishDirections = [
  {
    title: 'Sports Pathway – Champion Development',
    tag: 'Champion Pathway™',
    details: 'Sports & Performance Development',
    text: 'For students who want to develop discipline, team spirit and their sporting potential. Additional training, sports workshops, camps and competitions build coordination, strength, mental resilience, healthy habits and leadership through sport.',
    imageUrl: 'https://www.savremena-osnovna.edu.rs/wp-content/uploads/2026/02/sport.jpg',
  },
  {
    title: 'IT & AI Pathway – Digital Minds of the Future',
    tag: 'FutureTech Pathway™',
    details: 'IT, Coding & AI Exploration',
    text: 'For children who do not just want to use technology, but understand and create it. Coding, digital logic, age-appropriate AI projects, robotics and STEM challenges develop future-ready skills from the earliest years.',
    imageUrl: 'https://www.savremena-osnovna.edu.rs/wp-content/uploads/2026/02/it.jpg',
  },
  {
    title: 'Creative Arts Pathway – Studio of Ideas and Creativity',
    tag: 'Creative Studio Pathway™',
    details: 'Art, Design & Expression',
    text: 'For students who see the world through colour, ideas and creative expression. Visual arts, design, multimedia, creative projects and exhibitions develop imagination, aesthetics, confidence and art as a tool for thinking.',
    imageUrl: 'https://www.savremena-osnovna.edu.rs/wp-content/uploads/2026/02/art.jpg',
  },
  {
    title: 'Language & Global Skills Pathway – Languages Without Borders',
    tag: 'Global Language Pathway™',
    details: 'Languages, Cambridge & Communication',
    text: 'For students who want to speak to the world clearly, naturally and confidently. Advanced English, additional languages, international projects, communication skills and a global mindset prepare students for the Cambridge pathway and further education.',
    imageUrl: 'https://www.savremena-osnovna.edu.rs/wp-content/uploads/2026/02/language.jpg',
  },
]

const englishBenefits = [
  ['Interdisciplinary learning in English', 'English is part of every school day. Connecting different subjects helps students see the bigger picture, explain their ideas and apply what they learn in new situations.'],
  ['Recognised Cambridge qualifications', 'Cambridge qualifications support an international education journey. Preparing for them encourages deep understanding, strong study habits and confidence when choosing the next step.'],
  ['Modern technology in learning', 'Digital tools make abstract ideas more accessible. Through research and practical tasks, students discover how technology can support learning and the way they present their ideas.'],
  ['Experienced teachers and mentors', 'Experienced educators guide students through learning challenges. Feedback helps each student recognise what they already understand and where they can continue to grow.'],
  ['A commitment to every student', 'Attention to individual needs gives every student room to progress. Conversations about interests and goals encourage active participation and responsibility for their own learning.'],
  ['An inspiring learning environment', 'Dedicated mentoring support makes it easier to overcome challenges. When students feel free to ask questions, they build perseverance and confidence to try a different approach.'],
  ['Rich extracurricular activities', 'Sport and cultural experiences broaden the school journey. Shared activities create opportunities for new friendships, collaboration and discovering interests beyond the classroom.'],
  ['Clubs that develop talent', 'Clubs and workshops create space for self-expression. Through literature, art and languages, students discover their talents and find new ways to develop them.'],
].map(([title, text], index) => ({
  title,
  text,
  imageUrl: `https://www.international-school.edu.rs/wp-content/uploads/2026/09/is_benefits_${index + 1}.jpg`,
}))

const englishTestimonials = [
  {
    title: 'I have always wanted the best education',
    text: 'During the four years I spent at International School, I realised that the Cambridge programme was perfect for me. The school offers exceptional academic opportunities that every student can use to enrich their portfolio, while also creating a positive atmosphere thanks to its wonderful teachers.',
    author: 'Elena Ćuća',
    role: 'International School student',
    initials: 'EĆ',
    avatarImageUrl: 'https://www.international-school.edu.rs/wp-content/uploads/2026/09/elena_cuca.jpg',
    variant: 'text',
  },
  {
    title: 'As a parent, I can honestly say that I am incredibly proud',
    text: '',
    author: 'Tanja Anđelković',
    role: 'Parent',
    initials: 'TA',
    videoEmbedUrl: 'https://www.youtube.com/embed/pBLbcv5_2PI?start=21',
    videoImageUrl: 'https://www.international-school.edu.rs/wp-content/uploads/2026/09/testimonial_1.png',
    variant: 'video',
  },
  {
    title: 'A smoother path to university abroad',
    text: 'International School offers the programme and approach for children like mine, who completed primary school almost abroad, spent two years in Serbia and never truly found their place in that learning environment. We chose the Cambridge International programme because studying in English will make it easier for her to continue her education abroad.',
    author: 'Milica Prvulj',
    role: 'Miona’s mother',
    initials: 'MP',
    avatarImageUrl: 'https://www.international-school.edu.rs/wp-content/uploads/2026/09/Milica_privulj.jpg',
    variant: 'text',
  },
  {
    title: 'Prepare your child for a world where excellence is the standard!',
    text: 'I was impressed by the entire concept of the school and its approach to learning. Savremena fully supported my interests throughout all four years.',
    author: 'Tatjana Vilček',
    role: 'Principal of International School',
    initials: 'TV',
    videoEmbedUrl: 'https://www.youtube.com/embed/PW85NAwrm9c',
    videoImageUrl: 'https://www.international-school.edu.rs/wp-content/uploads/2026/09/testimonial_2.png',
    variant: 'video',
  },
  {
    title: 'An education that opened the doors to the world',
    text: 'I chose this school because the International programme opens many doors that other schools do not. It allows me to learn in a different environment, prepare for further education abroad and, most importantly, improve my English.',
    author: 'Uroš Jež',
    role: 'International School student',
    initials: 'UJ',
    avatarImageUrl: 'https://www.international-school.edu.rs/wp-content/uploads/2026/09/uros_jez.jpg',
    variant: 'text',
  },
]

export const defaultLandingData = {
  ...serbianLandingData,
  slug: 'en/why-wait',
  apiSlug: 'why-wait-en',
  locale: 'en',
  name: 'It is not too late for a better school',
  seo: {
    title: 'Make the most of your final opportunity to enrol at International School | 2026/27',
    description: 'Make the most of your final opportunity to enrol at International School. Cambridge education in English, an international environment and a confident path towards your child’s future.',
    ogImageUrl: 'https://www.international-school.edu.rs/wp-content/uploads/2026/09/is_nije_kasno_za_bolju_skolu_1200x628.jpg',
  },
  hero: {
    ...serbianLandingData.hero,
    eyebrow: 'Enrolment for the 2026/27 generation',
    title: 'Make the most of your final opportunity to enrol at International School',
    lead: 'Choose an education that prepares your child for the world.',
    note: 'Apply while places are available.',
  },
  emotionalTurn: {
    ...serbianLandingData.emotionalTurn,
    eyebrow: 'The right start makes all the difference',
    title: 'There is still time to make the right choice',
    text: 'There are only a few places left in some year groups. If you are already considering a change of school, now is the right moment to decide – your child can join a new class from the beginning, follow lessons naturally and build relationships with teachers and peers from day one.',
    paragraphs: [
      {
        text: 'Although the new school year has already begun, International School gives your child the opportunity to begin their journey to success right now. You do not have to wait until next year – your child can immediately become part of one of the schools offering the very best in education. Only a few places remain, so make the most of this opportunity!',
        bold: 'your child can immediately become part of one of the schools offering the very best in education.',
      },
      'If you are already considering a change of school, the beginning of the school year is the right time to decide – your child can settle into a new class more easily, follow lessons from the start and naturally build relationships with peers and teachers.',
      'Do not wait until the half-term or next school year to make a change that can have an important impact on your child’s education and future.',
    ],
    processTitle: 'What does the enrolment process look like?',
    processText: 'The process is simple. Submit the form online or call us on 011/40-11-220 and our admissions consultants will guide you through every step. The full procedure can be completed quickly, so your child can begin their new International School journey as soon as possible.',
    ctaText: 'Apply today and secure one of the remaining places.',
    worryLabel: 'Do you expect more from secondary education?',
    worries: [
      'Do you want a truly different education for your child?',
      'Do you want your child to learn in a modern school environment?',
      'Are you looking for a pathway that follows your child’s interests and talents?',
      'Do you want practical learning and future-ready skills?',
    ],
    reframeLabel: 'It is still not too late for a better school',
    reframes: ['Care and support', 'Modern learning', 'A confident future'],
  },
  specialConditions: {
    ...serbianLandingData.specialConditions,
    eyebrow: 'The meaning of number 9',
    title: 'Did you know why the number 9 is special?',
    paragraphs: [
      'As the largest single-digit number, nine symbolises fulfilment, achievement and the beginning of a new chapter. That is why it has special meaning for Savremena this year.',
      'Nine classes represent trust, continuous growth and the success that together open a new chapter in the school’s history.',
    ],
    ctaText: 'Apply while places are available.',
  },
  modernEducation: {
    ...serbianLandingData.modernEducation,
    eyebrow: 'Where innovation meets inspiration — and students thrive.',
    title: 'A Cambridge Future-Ready school in the heart of Belgrade',
    text: 'Children absorb much more than knowledge: values, confidence, language, ambition and a way of seeing the world.',
    paragraphs: [
      'A school is not just a place for learning. It is an environment that shapes a child’s thinking, confidence, curiosity, character and belief in their own possibilities every day.',
      'At International School, students aged 5 to 19 learn through the internationally recognised Cambridge programme in an atmosphere where excellence is not a distant goal, but the standard that surrounds them every day.',
      'Through knowledge, support, high expectations and a global outlook, students develop more than academic skills. They develop the belief that they can achieve more, think more broadly and move confidently towards the future.',
      'A child who grows up surrounded by the highest standards learns to reach them.',
    ],
  },
  directions: {
    ...serbianLandingData.directions,
    eyebrow: 'Talent Pathways™',
    title: 'Choose a pathway that follows your child’s interests',
    text: 'In the upper years, students choose a development module that follows, enriches and advances their interests and talents alongside the official curriculum.',
  },
  programChoice: {
    ...serbianLandingData.programChoice,
    eyebrow: 'Choose your path to success',
    title: 'National or Combined Cambridge programme',
    paragraphs: [
      'Every pathway can be followed through the National or Combined programme – a bilingual model that combines the national curriculum with elements of the official Cambridge curriculum.',
      'This carefully designed combination makes learning more accessible, while lessons in English create opportunities to earn national qualifications and prestigious Cambridge qualifications.',
      'A bilingual approach helps students develop their potential according to modern, globally relevant principles and prepares them for success anywhere in the world.',
    ],
  },
  benefits: {
    ...serbianLandingData.benefits,
    eyebrow: 'Truly different',
    title: 'Why is International School the best choice?',
    text: 'From the first school steps to preparation for university, International School connects Cambridge education in English with independence, talent development and life skills. In an international environment, students explore their interests and build confidence for new challenges.',
  },
  specialOffer: {
    ...serbianLandingData.specialOffer,
    eyebrow: 'An important step towards the future',
    title: 'Secure your place at International School',
    text: 'If your child has not enrolled at the school they hoped for, there is still an opportunity to choose an education that provides security, support and better preparation for the future.',
  },
  enrollmentHelp: {
    ...serbianLandingData.enrollmentHelp,
    title: 'Do you have questions or need help with enrolment?',
    introBeforeName: 'Our friendly and experienced admissions adviser,',
    introAfterName: 'is here to provide all the information you need, answer your questions and help you make the best decision for your child’s future.',
    emphasis: 'Do not wait – give your child an education that truly makes a difference.',
    prompt: 'Call us today and start your International School journey:',
    viberLabel: 'Viber',
    whatsappLabel: 'WhatsApp',
    contactSuffix: 'or complete the form and we will call you back.',
    closing: 'Your child’s successful academic future starts with one call.',
  },
  leadForm: {
    ...serbianLandingData.leadForm,
    formName: 'why-wait - is - en',
    namePlaceholder: 'Full name',
    countryCodeLabel: 'Country calling code',
    areaCodePlaceholder: '64',
    areaCodeLabel: 'Area code',
    phonePlaceholder: '1234567',
    phoneLabel: 'Phone',
    childAgePlaceholder: 'Child’s age',
    childAgeLabel: 'Child’s age',
    submitLabel: 'Apply now',
    successTitle: 'Your application has been sent',
    successMessage: 'Thank you. Our team will contact you shortly with information about enrolment.',
    errorMessage: 'Your application could not be sent at this time. Please try again or call us.',
  },
  testimonials: {
    eyebrow: 'Student and parent experiences',
    title: 'The Cambridge International programme allows me to learn in a different environment',
    text: '',
  },
  directionCards: englishDirections,
  benefitCards: englishBenefits,
  testimonialCards: englishTestimonials,
  footer: {
    ...serbianLandingData.footer,
    addressLine2: 'Belgrade',
    secondaryAddress: 'Terazije 23, Belgrade',
  },
}
